version: '3.11'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single-node
    mem_limit: 2g

  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    environment:
      - DJANGO_DB_NAME=$DB_DATABASE
      - DJANGO_DB_USER=$DB_USER
      - DJANGO_DB_PASSWORD=$DB_PASSWORD
      - DJANGO_DB_HOST=$DB_HOST
      - DJANGO_DB_PORT=$DB_PORT
    volumes:
      - .:/app
      - media_volume:/home/zzzz/PycharmProjects/Pinterest-Backend/media
    depends_on:
      - db
      - elasticsearch
#      - celery
#      - redis

  db:
    image: postgres:15.3-alpine
    container_name: db
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=$DB_DATABASE
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_HOST=$DB_HOST
      - POSTGRES_PORT=$DB_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  media_volume:
  postgres_data:

